name: Auto Deploy Dashboards

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout repository
        uses: actions/checkout@v3

      - name:  Copy and rename homework dashboards to index.html
        run: |
          for folder in 312540006_hw*; do
            if [ -f "$folder/312540006.html" ]; then
              cp "$folder/312540006.html" "$folder/index.html"
            fi
          done

      - name:  Generate Dashboard Landing Page
        run: |
          mkdir -p docs
          {
            echo "<!DOCTYPE html><html><head><title>Dashboard Index</title></head><body>"
            echo "<h1>Dashboard Index</h1><ul>"
            for folder in 312540006_hw* data_viz_project*; do
              if [ -f "$folder/index.html" ]; then
                echo "<li><a href=\"../$folder/\">$folder</a></li>"
              fi
            done
            echo "</ul></body></html>"
          } > index.html

      - name:  Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name:  Upload site content
        uses: actions/upload-pages-artifact@v2
        with:
          path: .

      - name:  Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
