name: Auto Deploy Dashboards

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout repository
        uses: actions/checkout@v3

      - name: 🪄 Rename *.html files to index.html in homework folders
        run: |
          for folder in 312540006_hw*; do
            html_file=$(find "$folder" -name "*.html" | head -n 1)
            if [ -f "$html_file" ]; then
              cp "$html_file" "$folder/index.html"
              echo " Copied $html_file → $folder/index.html"
            fi
          done

      - name:  Generate Landing Page at root
        run: |
          {
            echo "<!DOCTYPE html><html><head><title>Dashboard Index</title></head><body>"
            echo "<h1>Dashboard Index</h1><ul>"
            for folder in 312540006_hw* data_viz_project*; do
              if [ -f \"$folder/index.html\" ]; then
                echo "<li><a href=\"$folder/\">$folder</a></li>"
              fi
            done
            echo "</ul></body></html>"
          } > index.html

      - name:  Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name:  Upload full repository content
        uses: actions/upload-pages-artifact@v2
        with:
          path: .

      - name:  Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
